FROM openjdk:11-jre-slim-stretch
COPY target/matchups-discord-bot-1.0.0-shaded.jar /gmo/matchups-discord-bot-1.0.0-shaded.jar
CMD ["/usr/bin/java", "-jar", "/gmo/matchups-discord-bot-1.0.0-shaded.jar"]
